name: API Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  newman:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman collection
        run: newman run ./postman/serverest-collection.json -e ./postman/serverest-environment.json
